"""Initial

Revision ID: 9e22c0a41852
Revises:
Create Date: 2024-12-25 15:03:31.454504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e22c0a41852'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs',
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='pdfstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('total_page_count', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employment_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('file_hash')
    )
    op.create_index(op.f('ix_pdfs_file_hash'), 'pdfs', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdfs_file_hash'), table_name='pdfs')
    op.drop_table('pdfs')
    # ### end Alembic commands ###
